name: Build and Release

on:
  push:
    branches: [main]
    tags: ["*"]

permissions:
  contents: write
  issues: write
  pull-requests: write

env:
  GODOT_URL: "https://github.com/godotengine/godot-builds/releases/download"
  GODOT_VERSION: "4.4.1-stable"
  GODOT_PACKAGE_NAME: "Godot_v4.4.1-stable"
  GODOT_EXPORT_TEMPLATE_DIR: "4.4.1.stable.mono"
  EXPORT_NAME: "Stardgot"
  DOTNET_SDK_VERSION: "8.0"

jobs:
  build:
    name: Build (${{ matrix.target }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [Linux, Windows]
        include:
          - target: Linux
            export_name: Stardgot.x86_64
            godot_export: Linux
            artifact_name: linux-build
            build_path: build/Linux/
          - target: Windows
            export_name: Stardgot.exe
            godot_export: "Windows Desktop"
            artifact_name: windows-build
            build_path: build/Windows/
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_SDK_VERSION }}

      - name: Cache Godot and dependencies
        uses: actions/cache@v4
        with:
          path: |
            .godot/
            .nuget/
            ~/.local/share/godot/
          key: ${{ runner.os }}-godot-${{ env.GODOT_VERSION }}-${{ hashFiles('**/*.csproj', '**/project.godot') }}
          restore-keys: |
            ${{ runner.os }}-godot-${{ env.GODOT_VERSION }}-
            ${{ runner.os }}-godot-

      - name: Download and setup Godot
        run: |
          wget -nv ${GODOT_URL}/${GODOT_VERSION}/${GODOT_PACKAGE_NAME}_mono_linux_x86_64.zip
          wget -nv ${GODOT_URL}/${GODOT_VERSION}/${GODOT_PACKAGE_NAME}_mono_export_templates.tpz
          unzip -qq ${GODOT_PACKAGE_NAME}_mono_linux_x86_64.zip
          unzip -qq ${GODOT_PACKAGE_NAME}_mono_export_templates.tpz
          mkdir -p ~/.local/share/godot/export_templates/${GODOT_EXPORT_TEMPLATE_DIR}
          mv templates/* ~/.local/share/godot/export_templates/${GODOT_EXPORT_TEMPLATE_DIR}/
          chmod +x ${GODOT_PACKAGE_NAME}_mono_linux_x86_64/${GODOT_PACKAGE_NAME}_mono_linux.x86_64

      - name: Import project and build
        run: |
          export DISPLAY=:99
          Xvfb :99 -ac -screen 0 1024x768x24 &
          ./${GODOT_PACKAGE_NAME}_mono_linux_x86_64/${GODOT_PACKAGE_NAME}_mono_linux.x86_64 --headless --import --quit
          dotnet build
          ./${GODOT_PACKAGE_NAME}_mono_linux_x86_64/${GODOT_PACKAGE_NAME}_mono_linux.x86_64 --headless --export-release "${{ matrix.godot_export }}" ${{ matrix.build_path }}${{ matrix.export_name }}

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.build_path }}*
          retention-days: 1

  package:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Download Linux build
        uses: actions/download-artifact@v4
        with:
          name: linux-build
          path: build/Linux/

      - name: Download Windows build
        uses: actions/download-artifact@v4
        with:
          name: windows-build
          path: build/Windows/

      - name: Install semantic-release and plugins
        run: npm install -g semantic-release @semantic-release/changelog @semantic-release/git @semantic-release/github

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: semantic-release
